# WhatATheme
markdown: kramdown

# URL of the Site
url:
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Zetao Xu
# Description of the Site
description: A Linguist/Syntactician
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: zetaoxu@link.cuhk.edu.hk
facebook_username: Steven Xu
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Zetao Xu
# URL for the Image of the Author
author-image: /WhatATheme/assets/images/PF.jpg

# 60 Words About the Author
author-about: <font size=4> Hi! Welcome to my page. My name is Zetao Xu (徐泽韬), which is pronounced as [tsɣ<sup>35</sup> <sup>h</sup>tɑu<sup>55</sup> ɕy<sup>35</sup>]. I am a PhD student at the 

Chinese University of Hong Kong (CUHK), co-supervised by professor<a href="https://ling.cuhk.edu.hk/people/faculty-linguistics/pan-victor-junnan-personal-website/">Victor Junnan 
    Pan</a>(CUHK) and professor<a href="https://www.robertadalessandro.it/">Roberta 
    
    D'Alessandro</a>(Utrecht University). My research interests involve:<br> 

    
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  • Chinese syntax (Mandarin, Wu dialect) <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  • Heritage Chinese syntax in Europe <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  • Language contact and variation <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  • Indigenous languages in western China (nDrapa) 

   
  
    
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.researchgate.net/profile/Zetao-Xu-2

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
